name: Build site

on:
  workflow_dispatch:
  push:

concurrency: # Prevent two instances of this running at once
  group: deploy-to-ghpages
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: npm install
        run: npm install

      - name: "Build"
        run: "npm run build"

      - name: Generate deploy artefact
        run: zip -r ../site.zip *
        working-directory: public
        
      - name: Publish site
        run: "curl -Lf -X POST -u palmatum-service:${{ secrets.ACCESS_TOKEN }} -F siteName=readingList -F archive=@site.zip https://pages.tdpain.net/-/upload"
